# Generated by Django 5.2.17 on 2026-10-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('ADMIN_COMPANY', 'Admin Empresa'), ('OPERATOR', 'Operador'), ('VIEWER', 'Viewer'), ('CLIENT', 'Cliente')], max_length=30),
        ),
    ]
