# Generated by Django 5.2.17 on 2026-09-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('company', models.CharField(blank=True, default='', max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('scope', models.CharField(choices=[('nacional', 'Nacional'), ('internacional', 'Internacional')], max_length=20)),
                ('service_type', models.CharField(max_length=50)),
                ('origin_country', models.CharField(max_length=80)),
                ('origin_zip', models.CharField(max_length=12)),
                ('dest_country', models.CharField(max_length=80)),
                ('dest_zip', models.CharField(max_length=12)),
                ('dest_city', models.CharField(blank=True, default='', max_length=80)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('length_cm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('width_cm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pieces', models.PositiveIntegerField(default=1)),
                ('declared_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('requires_insurance', models.BooleanField(default=False)),
                ('urgency', models.CharField(choices=[('economico', 'Económico'), ('express', 'Express'), ('prioritario', 'Prioritario')], max_length=20)),
                ('frequency', models.CharField(choices=[('unico', 'Único'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], max_length=20)),
                ('pickup', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('result_weight', models.JSONField(default=dict)),
                ('result_options', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
