# Generated by Django 5.2.17 on 2026-09-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('company', models.CharField(blank=True, default='', max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=30)),
                ('pickup_address_line1', models.CharField(max_length=180)),
                ('pickup_city', models.CharField(max_length=80)),
                ('pickup_zip', models.CharField(max_length=12)),
                ('pickup_country', models.CharField(default='México', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
