# Generated by Django 5.2.17 on 2026-09-03 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='quotes.customer'),
        ),
    ]
