# Generated by Django 5.2.17 on 2026-10-06 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('quotes', '0004_rename_company_to_company_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_customers', to='companies.company'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_requests', to='companies.company'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='dest_area',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='dest_state',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='origin_area',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='origin_city',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='origin_state',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='provider_quotation_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='dest_country',
            field=models.CharField(default='MX', max_length=80),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='frequency',
            field=models.CharField(blank=True, choices=[('unico', 'Único'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='length_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='origin_country',
            field=models.CharField(default='MX', max_length=80),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='scope',
            field=models.CharField(choices=[('nacional', 'Nacional'), ('internacional', 'Internacional')], default='nacional', max_length=20),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='service_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='urgency',
            field=models.CharField(blank=True, choices=[('economico', 'Económico'), ('express', 'Express'), ('prioritario', 'Prioritario')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='width_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='QuoteParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length_cm', models.PositiveIntegerField()),
                ('width_cm', models.PositiveIntegerField()),
                ('height_cm', models.PositiveIntegerField()),
                ('weight_kg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='quotes.quoterequest')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
